// <auto-generated />
namespace HikersConnection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SplittingdataandtimeinHike : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SplittingdataandtimeinHike));
        
        string IMigrationMetadata.Id
        {
            get { return "201706011529338_Splitting data and time in Hike"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
